---
# Banner
banner_title: 'Susy'
banner_url: '/'
banner_tagline: 'your layout | <em>our math</em>'


# Author
site_author: 'Eric Suzanne'
site_author_url: 'http://twitter.com/ericmsuzanne'


# Version
versions:
  - title: 'Version'
    number: '2.1.1'
    notes: 'http://susydocs.oddbird.net/en/latest/changelog/'
    upgrade: 'http://susydocs.oddbird.net/en/latest/upgrade/'
    code: 'https://github.com/ericam/susy/'


# Videos
videos:
  - object: '<iframe src="//player.vimeo.com/video/93045089?title=0&amp;byline=0&amp;portrait=0&amp;color=ff0080" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'


# News
news:
  - title: 'Susy (For Sass) Now Supported'
    author: 'Chris Coyier'
    source: 'CodePen'
    url: 'http://blog.codepen.io/2014/08/21/susy-sass-now-supported/'
    type: 'article'
    tutorial_version: False
    feature: True

  - title: 'Susy Grid Grab Bag'
    author: 'Micah Godbolt'
    source: 'SassBites'
    url: 'https://www.youtube.com/watch?v=O8APW7ogrIw'
    type: 'video'
    tutorial_version: -2
    feature: True

  - title: 'Putting Susy Grids to Work'
    author: 'Micah Godbolt'
    source: 'SassBites'
    url: 'https://www.youtube.com/watch?v=rBKfH8UTn7w'
    type: 'video'
    tutorial_version: -2
    feature: True

  - title: 'Susy Grids - Layout Settings'
    author: 'Micah Godbolt'
    source: 'SassBites'
    url: 'https://www.youtube.com/watch?v=B31uLW6Vg24'
    type: 'video'
    tutorial_version: -2
    feature: True

  - title: 'Susy RWD Marker'
    author: 'Chris Maxwell'
    url: 'http://www.chrismaxwell.com/susy-rwd-marker'
    type: 'tutorial'
    tutorial_version: -1
    feature: False

  - title: 'Susy 102 - Breakpoints'
    author: 'Chris Maxwell'
    url: 'http://www.chrismaxwell.com/susy-102-breakpoints'
    type: 'tutorial'
    tutorial_version: -1
    feature: False

  - title: 'Susy 101 - Spanning Columns'
    author: 'Chris Maxwell'
    url: 'http://www.chrismaxwell.com/susy-101-spanning-columns'
    type: 'tutorial'
    tutorial_version: -1
    feature: False

  - title: 'Setting Up Susy'
    author: 'Chris Maxwell'
    url: 'http://www.chrismaxwell.com/setting-up-susy'
    type: 'tutorial'
    tutorial_version: -1
    feature: False

  - title: 'Making the Envato Marketplaces Responsive'
    author: 'Jordan Lewis'
    source: 'We build Envato'
    url: 'http://webuild.envato.com/blog/making-the-envato-marketplaces-responsive/'
    type: 'article'
    tutorial_version: False
    feature: True

  - title: 'Responsive: A Harrowing Meditation on the Brutal Realities of Web Content Organization, in 5 Acts'
    author: 'Stephany Varga'
    source: 'Zendesk Creative Collection'
    quote: 'Susy and Zendesk have been getting along magically... It’s precisely what you need and nothing more.'
    url: 'https://medium.com/zendesk-creative-blog/responsive-a-harrowing-meditation-on-the-brutal-realities-of-web-content-organization-in-5-acts-1d33ce25f062'
    type: 'article'
    tutorial_version: False
    feature: True

  - title: 'Susy Tutorials (11 Parts)'
    author: 'Scott Tolinski'
    source: 'Level Up Tuts'
    url: 'http://leveluptuts.com/tutorials/susy-tutorials'
    type: 'video'
    tutorial_version: -2
    feature: False

  - title: 'Your Own Damn [Susy] System'
    author: 'Eric M Suzanne'
    url: 'https://vimeo.com/93045089'
    type: 'video'
    tutorial_version: -2
    feature: False

  - title: 'Static Grids with Susy 2'
    author: 'Zell Liew'
    url: 'http://www.zell-weekeat.com/static-grids-with-susy2/'
    type: 'tutorial'
    tutorial_version: -2
    feature: False

  - title: 'My Favorite Sass Tools'
    quote: 'If you’re interested in reading Sass poetry, be sure to look at Susy’s source code!'
    author: 'Hugo Giraudel'
    source: 'SitePoint'
    url: 'http://www.sitepoint.com/my-favorite-sass-tools/'
    type: 'article'
    tutorial_version: False
    feature: False

  - title: 'Susy Grids 2.0 with Eric M. Suzanne'
    author: 'Micah Godbolt'
    source: 'SassBites'
    url: 'https://www.youtube.com/watch?v=m7k-vBzebPg'
    type: 'video'
    tutorial_version: -2
    feature: False

  - title: 'A Complete Tutorial to Susy 2 (Part 2)'
    author: 'Zell Liew'
    url: 'http://www.zell-weekeat.com/susy2-tutorial-2/'
    type: 'tutorial'
    tutorial_version: -2
    feature: False

  - title: 'A Complete Tutorial to Susy 2 (Part 1)'
    author: 'Zell Liew'
    url: 'http://www.zell-weekeat.com/susy2-tutorial/'
    type: 'tutorial'
    tutorial_version: -2
    feature: False

  - title: 'Adding Susy for Responsive Grids'
    author: 'Ray Villalobos'
    source: 'lynda.com'
    url: 'http://www.lynda.com/CSS-tutorials/Adding-Susy-responsive-grids/140777/153470-4.html'
    type: 'video'
    tutorial_version: -1
    feature: False

  - title: 'Responsive and Flexible Grids'
    author: 'Ben Frain'
    source: 'Sass & Compass for Designers'
    url: 'http://sassandcompass.com/chapter5/'
    type: 'book chapter'
    tutorial_version: -1
    feature: False

  - title: 'A Complete Tutorial to Susy'
    author: 'Zell Liew'
    url: 'http://www.zell-weekeat.com/a-complete-tutorial-to-susy/'
    type: 'tutorial'
    tutorial_version: -1
    feature: False

  - title: 'It’s Alive: Prototyping in the Browser'
    author: 'Patrick Marsceill'
    source: 'Happy Cog'
    url: 'http://cognition.happycog.com/article/its-alive-prototyping-in-the-browser'
    type: 'article'
    tutorial_version: False
    feature: False

  - title: 'Responsive Grids With Susy'
    author: 'Gabriel Manricks'
    source: 'Nettuts+'
    url: 'http://net.tutsplus.com/tutorials/html-css-techniques/responsive-grids-with-susy/'
    type: 'tutorial'
    tutorial_version: -1
    feature: False

  - title: 'Rapidfire 23'
    source: 'Shop Talk Show'
    url: 'http://shoptalkshow.com/episodes/102-rapidfire-23/#t=47:02'
    type: 'podcast'
    tutorial_version: False
    feature: False

  - title: 'Getting Started'
    url: 'http://susydocs.oddbird.net/en/latest/install/'
    type: 'docs'
    tutorial_version: -2
    feature: False

  - title: 'Upgrade Path'
    url: 'http://susydocs.oddbird.net/en/latest/upgrade/'
    type: 'docs'
    tutorial_version: -2
    feature: False

  - title: 'Different Grid Types'
    url: 'grid-types'
    type: 'docs'
    tutorial_version: -1
    feature: False

  - title: 'Mobile-First "Magic" Grids'
    url: 'magic'
    type: 'docs'
    tutorial_version: -1
    feature: False


# Screenshots
screenshots:
  - image: '/static/screenshots/sasslang.jpg'
    alt: 'Sass'
    target: 'http://sass-lang.com/'

  - image: '/static/screenshots/squaremarket.jpg'
    alt: 'Square Market'
    target: 'http://squareup.com/market'

  - image: '/static/screenshots/smithsonian.jpg'
    alt: 'Smithsonian'
    target: 'http://smithsonian.com/'

  - image: '/static/screenshots/python.jpg'
    alt: 'Python'
    target: 'http://python.org/'

  - image: '/static/screenshots/simple.jpg'
    alt: 'Simple'
    target: 'http://simple.com/'

  - image: '/static/screenshots/mediamolecule.jpg'
    alt: 'Media Molecule'
    target: 'http://mediamolecule.com'


# Intro
intro:
  - title: 'Your markup, your design, your opinions | <em>our math</em>.'
    id: no-opinions
    text: 'In a world of agile development
        and super-tablet-multi-magic-laptop-phones,
        the best layouts can’t be contained
        in a single framework or technique.
        CSS Libraries are a bloated mess of opinions
        about how to do your job.
        Why let the table-saw tell you where to put the kitchen?'


# Navigation
nav:
  - name: Documentation
    url: 'http://susydocs.oddbird.net/'
    icon: list
  - name: Tutorials
    url: '/demos/'
    icon: direction
  - name: Support
    url: 'http://stackoverflow.com/questions/tagged/susy-sass'
    icon: stackoverflow
  - name: Twitter
    url: 'http://twitter.com/sasssusy/'
    icon: twitter


# Credits
credit:
  - name: 'Tsachi Shlidor'
    url: http://twitter.com/shlidor
  - name: 'Aaron Gray'
    url: http://twitter.com/mragray
  - name: 'Jina'
    url: http://twitter.com/jina
  - name: 'Danny Palmer'
    url: http://twitter.com/dannyprose
  - name: 'Rachel Nabors'
    url: http://twitter.com/rachelnabors
  - name: 'Sam Richard'
    url: http://twitter.com/snugug
  - name: 'Scott Kellum'
    url: http://twitter.com/scottkellum
  - name: 'Mason Wendell'
    url: http://twitter.com/codingdesigner
  - name: 'many&nbsp;others'
    url: https://github.com/ericam/susy/graphs/contributors


# Colophon
colophon:
  - name: 'GitHub'
    url: https://github.com/ericam/susysite
  - name: 'rstBlog'
    url: http://github.com/mitsuhiko/rstblog/
  - name: 'Python'
    url: http://www.python.org/
  - name: 'Jinja'
    url: http://jinja.pocoo.org/
  - name: 'Compass'
    url: http://compass-style.org/
  - name: 'Sass'
    url: http://sass-lang.com
  - name: 'Susy'
    url: http://susy.oddbird.net
  - name: 'Breakpoint'
    url: http://breakpoint-sass.com
  - name: 'Pygments'
    url: http://pygments.org/
  - name: 'IcoMoon'
    url: http://icomoon.io
  - name: 'Source Sans Pro'
    url: https://github.com/adobe/source-sans-pro
  - name: 'Source&nbsp;Code&nbsp;Pro'
    url: https://github.com/adobe/source-code-pro


# Settings
active_modules: [pygments_simple, tags, blog, wrap, typogrify]
author: Eric
canonical_url: http://susy.oddbird.net/
output_folder: ../output
template_path: ../templates
rst_writer: html5writer
modules:
  pygments:
    style: borland
  blog:
    index_url: /blog/
